#pragma once

#define SAR_PUBLIC_CLOUD_HOST ""
#define SAR_PUBLIC_CLOUD_PORT 8884
#define SAR_PUBLIC_TOPIC_PREFIX "devices/"
#define SAR_PUBLIC_MIGRATION_API_URL ""
#define SAR_PUBLIC_PRESENCE_HOST ""
#define SAR_PUBLIC_UPDATE_HOST ""
#define SAR_PUBLIC_UPDATE_INFO_URL ""
